import builtins from "builtin-modules";
import esbuild from "esbuild";
import esbuildSvelte from "esbuild-svelte";
import process from "process";
import sveltePreprocess from "svelte-preprocess";
import { getGitInfo } from "./buildGitInfo.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Get git info for development builds only
const gitInfo = prod ? { branch: null, commitHash: null, hasUncommittedChanges: null } : getGitInfo();

// Define global constants that will be replaced at build time
const buildDefines = {
	__IS_DEV_BUILD__: JSON.stringify(!prod),
	__DEV_GIT_BRANCH__: JSON.stringify(gitInfo.branch),
	__DEV_GIT_COMMIT__: JSON.stringify(gitInfo.commitHash),
	__DEV_GIT_DIRTY__: JSON.stringify(gitInfo.hasUncommittedChanges),
};
const options = Object.freeze({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts", "src/styles.css"],
	bundle: true,
	minify: prod,
	define: buildDefines,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/closebrackets",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/comment",
		"@codemirror/fold",
		"@codemirror/gutter",
		"@codemirror/highlight",
		"@codemirror/history",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/matchbrackets",
		"@codemirror/panel",
		"@codemirror/rangeset",
		"@codemirror/rectangular-selection",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/stream-parser",
		"@codemirror/text",
		"@codemirror/tooltip",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	mainFields: ["svelte", "browser", "module", "main"],
	plugins: [
		esbuildSvelte({
			compilerOptions: { css: "injected" },
			preprocess: sveltePreprocess(),
		}),
	],
	format: "cjs",
	target: "ES2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: ".",
});

if (!prod) {
	const context = await esbuild.context(options);

	await context.watch();
} else {
	esbuild.build(options).catch(() => process.exit(1));
}
