name: Build With Lint

on:
    pull_request:
        branches:
            - master
    workflow_dispatch:

jobs:
    build-with-lint:
        name: Build With Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: |
                  bun install
            - name: Run build with lint
              run: |
                  bun run build-with-lint
